name: 'Get Version Tag'
description: 'Find the git tag that looks like a version and outputs that version for use in other actions'
branding:
  icon: 'tag'
  color: 'gray-dark'
outputs:
  version:
    description: 'The version, without a leading "v"'
  version-with-v:
    description: 'The version, with a leading "v"'
runs:
  using: 'node12'
  main: 'main.js'
