name: Continuous Integration
on:
  push:
    branches:
      - 'main'
  pull_request:
jobs:
  get-previous-tag:
    name: Test Get Version Tag on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      
      - run: git tag v0.1.0

      - name: 'Get Version Tag'
        id: versiontag
        uses: ./

      - run: git tag -d v0.1.0
      
      - run: echo "${{ steps.versiontag.outputs.version }}, ${{ steps.versiontag.outputs.version-with-v }}"
