name: Continuous Integration
on:
  push:
    branches:
      - 'master'
  pull_request:
jobs:
  get-previous-tag:
    name: Test Get Previous Tag on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: 'Get Previous tag'
        id: previoustag
        uses: ./
      - run: |
          echo "${{ steps.previoustag.outputs.tag }}"
      - name: Remove tags
        uses: JesseTG/rm@v1.0.2
        with:
          path: .git/refs/tags
      - name: 'Get Previous tag with fallback'
        id: previoustagwithfallback
        uses: ./
        with:
          fallback: v1.0.0
      - run: |
          echo "${{ steps.previoustagwithfallback.outputs.tag }}"
